### ISSUE TITLE
Ensure ability to read containers rpmdb

### ISSUE THREAD

**Issue by kolyshkin** [openshift/check-payload#100]
Node scan (and, since #78, payload scan) uses host rpm binary to read containers' (images') rpmdb. Surely, host and container can have very different rpm versions, configurations etc.

I have already added a hack so it works when host and container has different rpmdb path in #83 (see https://github.com/openshift/check-payload/commit/84988f89885fc3f2bde267aefae41cdbc22a6043).

Apparently, some more work is needed to ensure host rpm is working for all containers. In particular, @rphillips reported a failure to read rpmdb in https://github.com/openshift/check-payload/pull/98#issuecomment-1660405049.

It is not yet clear if we can fix this by adding some more options to host rpm, but I hope we can.

The alternative is to use container's rpm via chroot. This will work without further hacks, but the downsides are:
 - we have to trust container's rpm binary (and since we're a security tool to check containers binaries, this sounds crazy);
 - the container must have the same architecture as the host (not an issue currently, I guess).

**Comment by rphillips** [comment]
It looks like some images are older base images which include a RPM (4.14.3) binary using BDB instead of sqlite.

**Comment by rphillips** [comment]
Arch linux needs the rpm-tools package built with `--enable-bdb-ro`.

**Comment by kolyshkin** [comment]
OK, the issue was `rpm` binary in ArchLinux was not compiled with bdb support, and so it was not able to fall back to it.

This was reported in https://bugs.archlinux.org/task/74810 (and https://bugs.archlinux.org/task/79270) and fixed in https://gitlab.archlinux.org/archlinux/packaging/packages/rpm-tools/-/commit/1440710c44a6f3bfd30f9a74ad62545fcbe461dc (rpm 4.18.1-3).

**Comment by kolyshkin** [comment]
This is how to repro this locally (sorry, old comment, forgot to click "Comment"):

```console
# podman image mount quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:91e37c277d80facba198afcbb05c06c0f27b6f9c7bb4f2dd64cf12e331a0dc58
/run/media/kir/8885b6f8-2cc0-4416-b5e9-dfecb3137d9a/containers-root/storage/overlay/c93cd2fcf72b3e0ff7c83e661efafead4bf8fab631cd7c4e7aedf12acacd83a8/merged

# podman run -it -v /run/media/kir/8885b6f8-2cc0-4416-b5e9-dfecb3137d9a/containers-root/storage/overlay/c93cd2fcf72b3e0ff7c83e661efafead4bf8fab631cd7c4e7aedf12acacd83a8/merged:/img -v ./check-payload:/check-payload archlinux

[root@7cb5f166fef5 /]# pacman -Sy
...

[root@7cb5f166fef5 /]# pacman -S binutils rpm-tools
...

[root@7cb5f166fef5 /]# ./check-payload scan node --root /img/
---- Failure Report
+----------------------------------------------------------------------------------------------------------------------------------------+
| STATUS                                                                                                                                 |
+----------------------------------------------------------------------------------------------------------------------------------------+
| rpm -qa error: exit status 1 (stderr=error: Unable to open sqlite database /img/var/lib/rpm/rpmdb.sqlite: unable to open database file |
| error: cannot open Packages index using sqlite - Operation not permitted (1)                                                           |
| error: cannot open Packages database in /img/var/lib/rpm                                                                               |
| )                                                                                                                                      |
```
