### ISSUE TITLE
Removing the root config file

### ISSUE THREAD

**Issue by rphillips** [openshift/check-payload#76]
The config file at the root isn't necessarily needed since we almost always use a versioned (4.12, 4.11, etc) config file.

We can remove the root config file and document how the config files are used.

**Comment by kolyshkin** [comment]
It won't play well for e.g. node scan, as main config file has a bunch of directories to filter out. 

Also, PTAL #80 where I made all payloads (4.9 to 4.12) work with a single config (main config, that is) using rpm-based rules. Meaning, we might be just fine using a single config for all releases.

If not, I think we should make the per-version config amend the main one.

**Comment by kolyshkin** [comment]
@rphillips I think that with #86 in place, which made versioned config add-ons to the main one, we can close this issue.
