### ISSUE TITLE
go: binary has zero tags enabled (should have strictfipsruntime)

### ISSUE THREAD

**Issue by dominikholler** [openshift/check-payload#81]
If the GOEXPERIMENT=strictfipsruntime is used, the check-payload, there is no tag for strictfipsruntime created, and the check-payload tool complains about `go: binary has zero tags enabled (should have strictfipsruntime)`

**Comment by kolyshkin** [comment]
@dominikholler are you suggesting that we should check for tag, and if not found, fall back to checking if `GOEXPERIMENT=strictfipsruntime` is set, and fail only if neither is set?

Can you point out to a binary that has `GOEXPERIMENT=strictfipsruntime` set?

**Comment by dollierp** [comment]
> @dominikholler are you suggesting that we should check for tag, and if not found, fall back to checking if `GOEXPERIMENT=strictfipsruntime` is set, and fail only if neither is set?
> 

Yes, it seems there are currently two situations were the check-payload tool report false positive:

1. compiling with only `GOEXPERIMENT=strictfipsruntime` and no `-tags` at all is reported by the tool as a warning `go: binary has zero tags enabled (should have strictfipsruntime)`
2. compiling with `GOEXPERIMENT=strictfipsruntime` and another tag e.g. `-tags selinux` is reported by the tool as a warning `go: binary does not contain required tag strictfipsruntime`

**Comment by dominikholler** [comment]
@dbenoit17 is the tag still required, if `GOEXPERIMENT=strictfipsruntime` is set?
